# Generated by Django 5.2.12 on 2026-04-09 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_category_slugs(apps, schema_editor):
    ServiceCategory = apps.get_model("services", "ServiceCategory")
    used = set()
    for category in ServiceCategory.objects.all().order_by("id"):
        base = slugify(category.name) or "category"
        candidate = base
        idx = 2
        while candidate in used or ServiceCategory.objects.filter(slug=candidate).exclude(pk=category.pk).exists():
            candidate = f"{base}-{idx}"
            idx += 1
        category.slug = candidate
        category.save(update_fields=["slug"])
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RunPython(populate_category_slugs, migrations.RunPython.noop),
    ]
