# Generated by Django 5.2.12 on 2026-04-09 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_subscription_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model("accounts", "SubscriptionPlan")
    defaults = [
        ("Starter", "0.00", 3, 5),
        ("Pro", "50.00", 10, 20),
        ("Business", "100.00", -1, -1),
    ]
    for name, price, max_services, max_bookings in defaults:
        SubscriptionPlan.objects.update_or_create(
            name=name,
            defaults={
                "price": price,
                "max_services": max_services,
                "max_bookings_per_day": max_bookings,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_services', models.IntegerField(default=3)),
                ('max_bookings_per_day', models.IntegerField(default=5)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='snapchat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.subscriptionplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.RunPython(seed_subscription_plans, migrations.RunPython.noop),
    ]
