# Generated by Django 5.2.12 on 2026-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriptionplan_providerprofile_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='mobile_money_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='mobile_money_network',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
