# Generated by Django 5.2.12 on 2026-04-09 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_provider(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for booking in Booking.objects.select_related("service__provider").all():
        if booking.provider_id is None and booking.service_id:
            booking.provider_id = booking.service.provider_id
            booking.save(update_fields=["provider"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_provider, migrations.RunPython.noop),
    ]
